FROM ubuntu:xenial

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y git sudo python python3-dev python3 python3-venv ca-certificates unzip openssh-server mongodb mysql-server mysql-client unzip gcc make
RUN apt-get install -y software-properties-common && add-apt-repository --yes ppa:jonathonf/firefox-esr-52 && apt-get update && apt-get install -y firefox-esr
RUN echo 'deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main' >> /etc/apt/sources.list.d/pgdg.list && wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | apt-key add - && apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y postgresql-10
WORKDIR /opt
RUN git clone https://github.com/open-craft/opencraft ocim
RUN make -C ocim install_system_dependencies
RUN python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip && pip install --upgrade virtualenv && pip install -r ocim/requirements.txt && pip install -r ocim/cleanup_utils/requirements.txt
RUN wget -P /tmp https://releases.hashicorp.com/consul/1.2.1/consul_1.2.1_linux_amd64.zip && sudo unzip /tmp/consul_1.2.1_linux_amd64.zip -d /usr/local/bin
